FeedApp/urls.py
from django.urls import path
from . import views

app_name = 'FeedApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/',views.profile,name='profile'),
    path('myfeed',views.myfeed, name='myfeed'),
    path('new_post/', views.new_post, name='new_post'),
    path('friendsfeed',views.friendsfeed, name='friendsfeed'),
    path('comments/<int:post_id>/',views.comments,name='comments'),
    path('friends',views.friends, name='friends'),
    ]

    

FeedProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FeedApp.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views


app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    ]

FeedApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    first_name = models.CharField(max_length=200,blank=True)
    last_name = models.CharField(max_length=200,blank=True)
    email = models.EmailField(max_length=300,blank=True)
    dob = models.DateField(null=True, blank=True)
    bio = models.TextField(blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField(User,blank=True, related_name='friends')
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.user.username}"

STATUS_CHOICES = (
    ('sent','sent'),
    ('accepted','accepted')
)

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES, default="sent")
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    

class Post(models.Model):
    description = models.CharField(max_length=255, blank=True)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images',blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    username = models.ForeignKey(User, related_name='details', on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.text
    
    
class Like(models.Model):
	username = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
	post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)

FeedApp/forms.py
from django import forms
from .models import Post, Profile, Relationship

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['description','image']
        labels = {'description': 'What would you like to say?'}


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name','last_name','email','dob','bio']
        labels = {'first_name':'First Name',
                    'last_name':'Last Name',
                    'email':'Email',
                    'dob':'Date of Birth',
                    'bio':'Bio'}

class RelationshipForm(forms.ModelForm):
    class Meta:
        model = Relationship
        fields = '__all__'
        labels = {
            'sender':'Accept friend request from:',
            'receiver':'Send friend request to:',
            'status': 'Current status:'

        }

FeedApp/views.py
from django.shortcuts import render, redirect
from .forms import PostForm,ProfileForm, RelationshipForm
from .models import Post, Comment, Like, Profile, Relationship
from datetime import datetime, date

from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.

# When a URL request matches the pattern we just defined, 
# Django looks for a function called index() in the views.py file. 

def index(request):
    """The home page for Learning Log."""
    return render(request, 'FeedApp/index.html')



@login_required
def profile(request):
    profile = Profile.objects.filter(user=request.user)
    if not profile.exists():
        Profile.objects.create(user=request.user)
    profile = Profile.objects.get(user=request.user)

    if request.method != 'POST':
        form = ProfileForm(instance=profile)
    else: 
        form = ProfileForm(instance=profile,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('FeedApp:profile')

    context = {'form':form}
    return render(request, 'FeedApp/profile.html',context)


@login_required
def myfeed(request):
    comment_count_list = []
    like_count_list = []
    posts = Post.objects.filter(username=request.user).order_by('-date_posted')
    for p in posts:
        c_count = Comment.objects.filter(post=p).count()
        l_count = Like.objects.filter(post=p).count()
        comment_count_list.append(c_count)
        like_count_list.append(l_count)
    zipped_list = zip(posts,comment_count_list,like_count_list)

    context = {'posts':posts, 'zipped_list':zipped_list}
    return render(request, 'FeedApp/myfeed.html',context)


@login_required
def new_post(request):
    if request.method != 'POST':
        form = PostForm()
    else: 
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.username = request.user
            new_post.save()
            return redirect('FeedApp:myfeed')

    context = {'form':form}
    return render(request,'FeedApp/new_post.html',context)

@login_required
def friendsfeed(request):
    comment_count_list = []
    like_count_list = []
    friends = Profile.objects.filter(user=request.user).values('friends')    
    posts = Post.objects.filter(username__in=friends).order_by('-date_posted')
    for p in posts:
        c_count = Comment.objects.filter(post=p).count()
        l_count = Like.objects.filter(post=p).count()
        comment_count_list.append(c_count)
        like_count_list.append(l_count)
    zipped_list = zip(posts,comment_count_list,like_count_list)

    if request.method == "POST" and request.POST.get("like"):
        post_to_like = request.POST.get("like")
        print(post_to_like)
        like_already_exists = Like.objects.filter(post_id=post_to_like,username=request.user)
        if not like_already_exists.exists():
            Like.objects.create(post_id=post_to_like,username=request.user)
            return redirect("FeedApp:friendsfeed")

    context = {'posts':posts, 'zipped_list':zipped_list}
    return render(request, 'FeedApp/friendsfeed.html',context)


@login_required
def comments(request, post_id):
    if request.method == 'POST' and request.POST.get("btn1"):
        comment = request.POST.get("comment")
        Comment.objects.create(post_id=post_id, username=request.user, text=comment, date_added=date.today())

    comments = Comment.objects.filter(post=post_id)
    post = Post.objects.get(id=post_id)

    context = {'post':post, 'comments':comments}

    return render(request, 'FeedApp/comments.html',context)



@login_required
def friends(request):
    admin_profile = Profile.objects.get(user=1)

    user_profile = Profile.objects.get(user=request.user)


    user_friends = user_profile.friends.all()
    user_friends_profiles = Profile.objects.filter(user__in=user_friends)


    user_relationships = Relationship.objects.filter(sender=user_profile)
    request_sent_profiles = user_relationships.values('receiver')


    all_profiles = Profile.objects.exclude(user=request.user).exclude(id__in=user_friends_profiles).exclude(id__in=request_sent_profiles)



    request_received_profiles = Relationship.objects.filter(receiver=user_profile,status='sent')



    if not user_relationships.exists():
        Relationship.objects.create(sender=user_profile, receiver=admin_profile, status='sent')
        #relationship = Relationship.objects.filter(sender=user_profile, status='sent')




    if request.method == 'POST' and request.POST.get("send_requests"):
        receivers = request.POST.getlist("send_requests")
        print(receivers)
        for receiver in receivers:
            receiver_profile = Profile.objects.get(id=receiver)
            Relationship.objects.create(sender=user_profile, receiver=receiver_profile, status='sent')

        return redirect('FeedApp:friends')


    if request.method == 'POST' and request.POST.get("receive_requests"):
        senders = request.POST.getlist("receive_requests")
        for sender in senders:

            Relationship.objects.filter(id=sender).update(status='accepted')



            relationship_obj = Relationship.objects.get(id=sender)
            user_profile.friends.add(relationship_obj.sender.user)


            relationship_obj.sender.friends.add(request.user)

    context = {'user_friends_profiles':user_friends_profiles,'user_relationships':user_relationships,'all_profiles':all_profiles,'request_received_profiles':request_received_profiles}

    return render(request, 'FeedApp/friends.html', context)

FeedApp/templates/FeedApp/base.html
{% load bootstrap4 %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,
          shrink-to-fit=no">
        <title>Feed</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}

    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'FeedApp:index'%}">
            Home</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'FeedApp:profile' %}">My Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'FeedApp:friends' %}">Friend Requests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'FeedApp:myfeed' %}">My Feed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'FeedApp:friendsfeed' %}">Friends Feed</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
              </ul>
        </div>

        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>

            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>

    </body>




</html>

FeedApp/templates/FeedApp/comments.html
{% extends "FeedApp/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h2><p>Post: {{ post.description }} </p></h2>
<h2><p><img src="{{ post.image.url}}" class="img-thumbnail" style="max-height:300px" alt="No image"><br><br></p></h2>

    <form method="POST">
        {% csrf_token %}
        {% for c in comments %} 
        <li>
            <p> {{ c.text}} &nbsp -- &nbsp {{ c.username }}</p>
        </li>
        {% empty %} 
        <li>There are no comments for this post.</li>
        {% endfor %}
    <p><input type="text" name="comment"</p>
    <p><button type="submit" name="btn1" value=1>Submit Comment</button></p>

    </form>

{% endblock content %}

FeedApp/templates/FeedApp/friends.html
{% extends "FeedApp/base.html" %}
{% load bootstrap4 %}

{% block content %}

<style>
    table {
        font-size: 15px; width:auto; 
    }

    th,td {
        border: 1px solid black; padding: 6px;
    }
</style>

<h2><p>My Friends</p></h2>
<table>
    <tr>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Member Since</th>
    </tr>
    {% for friend in user_friends_profiles %}
    <tr>
        <td>{{friend}}</td>
        <td>{{friend.first_name}}</td>
        <td>{{friend.last_name}}</td>
        <td>{{friend.email}}</td>
        <td>{{friend.created|date:"M d Y"}}</td>
    </tr>
    {% endfor %}
</table>

<br><br>

<h2><p>Friend Requests sent</p></h2>
<table>
    <tr>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Date Sent</th>
        <th>Status</th>
    </tr>
    {% for r in user_relationships %}
    <tr>
        <td>{{r.receiver}}</td>
        <td>{{r.receiver.first_name}}</td>
        <td>{{r.receiver.last_name}}</td>
        <td>{{r.created}}</td>
        <td>{{r.status}}</td>

    </tr>
    {% endfor %}
</table>
<br><br>

<h2><p>Send a Friend Request</p></h2>
<form action="{% url 'FeedApp:friends' %}" method='post'>
    {% csrf_token %} 
    <table>
        <tr>
            <th>Users</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Request</th>
        </tr>
    {% for profile in all_profiles %}
    <tr>
        <td>{{profile}}</td>
        <td>{{profile.first_name}}</td>
        <td>{{profile.last_name}}</td>
        <td><input type="checkbox" name="send_requests" value="{{profile.id}}"></td>
    </tr>
    {% endfor %}
    </table>
    <br><br>
    <button name="submit" class="btn btn-outline-primary" style="float: left;">Send Request</button>
</form>

<br><br><br><br>

<h2><p>Friend Request received</p></h2>
<form action="{% url 'FeedApp:friends' %}" method='post'>
    {% csrf_token %} 
    <table>
        <tr>
            <th>Users</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Request</th>
        </tr>
    {% for rr in request_received_profiles %}
    <tr>
        <td>{{rr.sender}}</td>
        <td>{{rr.sender.first_name}}</td>
        <td>{{rr.sender.last_name}}</td>
        <td><input type="checkbox" name="receive_requests" value="{{rr.id}}"></td>
    </tr>
    {% endfor %}
    </table>
    <br><br>
    <button name="submit" class="btn btn-outline-primary" style="float: left;">Approve Request</button>
    <br><br><br><br>
</form>



{% endblock content %}

FeedApp/templates/FeedApp/friendsfeed.html
{% extends "FeedApp/base.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}


{% block content %}

<h1><p> Posts </p></h1>
<form method="POST">
{% csrf_token %}
<table style="font-size: 25px;width:100%;">

    {% for p,c,l in zipped_list %}
        <tr style="border: 1px solid black;padding: 6px;">
            <td> {{ p.username}}:&nbsp {{ p }} <br>
                {% if p.image %}
                <img src="{{p.image.url}}" class="img-thumbnail" style="max-height: 300px" alt="">
                {% endif %}
            </td>
        </tr>
        <tr style="border: 1px solid black;padding: 6px;">
            <td> {{p.date_posted}}</td>
            <td>
                <button type="submit" name="like" value={{p.id}} style="background-color: transparent;border:none;">
                Likes: &nbsp {{l}} 
                </button>
            </td>
            <td>Comments: &nbsp <a href="{% url 'FeedApp:comments' p.id %}">{{c}}</a>&nbsp&nbsp</td>
        </tr>
    {% endfor %}

</table>
</form>

{% endblock content %}

FeedApp/templates/FeedApp/index.html
{% extends "FeedApp/base.html" %}

{% block page_header %}
    <div class="jumbotron">
       <h1 class="display-3">Feed</h1>
            <p class="lead">A Social Network where you can be you.
            </p>

            <a class="btn btn-lg btn-outline-primary" href="{% url 'users:register' %}"
            role="button">Join Now &raquo;</a>
    </div>
{% endblock page_header %}

FeedApp/templates/FeedApp/myfeed.html
{% extends "FeedApp/base.html" %}
{% load bootstrap4 %}

{% block content %}

<h1><p>My Posts</p></h1>

<h3><a href="{% url 'FeedApp:new_post' %}">Add a new post</a></h3>

<table style="font-size: 25px;width:100%;">

    {% for p,c,l in zipped_list %}
        <tr style="border: 1px solid black;padding: 6px;">
            <td> {{ p.username}}:&nbsp {{ p }} <br>
                {% if p.image %}
                <img src="{{p.image.url}}" class="img-thumbnail" style="max-height: 300px" alt="">
                {% endif %}
            </td>
        </tr>
        <tr style="border: 1px solid black;padding: 6px;">
            <td> {{p.date_posted}}</td>
            <td>Likes: &nbsp {{l}} &nbsp&nbsp&nbsp</td>
            <td>Comments: &nbsp <a href="{% url 'FeedApp:comments' p.id %}">{{c}}</a>&nbsp&nbsp</td>
        </tr>
    {% endfor %}

</table>

{% endblock content %}

FeedApp/templates/FeedApp/new_post.html
{% extends "FeedApp/base.html" %}
{% load bootstrap4 %}

{% block content %}
  <h2><p>New Post:</p></h2>




<form action="{% url 'FeedApp:new_post' %}" method='post' enctype='multipart/form-data'>

    {% csrf_token %}
    {% bootstrap_form form %}

    <br><br>
    <button name="submit" class="btn btn-outline-primary">Post</button>
</form>


{% endblock content %}

FeedApp/templates/FeedApp/profile.html
{% extends "FeedApp/base.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block content %}

<h1><p>My Profile:</p></h1>

<form action="{% url 'FeedApp:profile' %}" method='post'>
    {% csrf_token %}
    {{ form |crispy}}
    <br><br>
    <button name="submit" class="btn btn-outline-primary">Update</button>
</form>


{% endblock content %}